parameters:
  - name: workingDirectory
    type: string
  - name: adoServiceConnectionName
    type: string
  - name: backendAzureRmResourceGroupName
    type: string
  - name: backendAzureRmStorageAccountName
    type: string
  - name: backendAzureRmContainerName
    type: string
  - name: backendAzureRmKey
    type: string
  - name: tfvarsFileName
    type: string

steps:
  - task: TerraformInstaller@0
    displayName: 'Terraform Install'
    inputs:
      terraformVersion: '$(terraform_version)'
  - task: TerraformTaskV4@4
    displayName: 'Terraform Destroy'
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      commandOptions: '-var-file "${{ parameters.tfvarsFileName }}"'
      workingDirectory: '${{ parameters.workingDirectory }}'
      environmentServiceNameAzureRM: '${{ parameters.adoServiceConnectionName }}'